### PR TITLE
Pluggable authentication module

### PR DESCRIPTION
**Pull request by sdissegna-maystreet**
This is the implementation of the suggestion described in #4068

### CODE REVIEW

**Comment by TeffenEllis** [comment]
Thank you so much for this contribution! We’ll need some time to review this proposal, but I feel optimistic this is a feature that many users could find helpful.

**Comment by jsjoeio** [comment]
This looks really neat! Thanks for opening an issue and adding. Like @TeffenEllis said, optimistic but we'll need to discuss a bit. 


Don't worry about the Docs preview failing - we have an issue running that on forks. (see https://github.com/cdr/code-server/issues/4027)

As for Build/Pre-build, it looks like you'll need to adjust some of the unit tests. Let us know if you need any guidance in that area.

Are you planning on adding docs or an example for how you imagine someone might use this?

**Comment by jsjoeio** [comment]
Okay, I just chatted with @code-asher briefly about this. We're going to start a discussion in your original issue.

According to [our docs](https://codercom-fz5ydumz2-codercom.vercel.app/docs/code-server/v3.11.1/CONTRIBUTING#creating-pull-requests):
> Please create a GitHub Issue that includes context for issues that you see. You can skip this if the proposed fix is minor.

Ideally, a change with large impact like this should be first discussed in an issue before a PR is opened. That way, we can ensure everyone is onboard and we understand how this will impact the community before the author begins implementing the feature. We'll leave this PR for now since this may not have been super clear. 

We'll continue the discussion on the issue and see how we can figure out a way to move forward with this idea.

**Comment by jsjoeio** [comment]
Hey @sdissegna-maystreet - hope you saw the discussion [here](https://github.com/cdr/code-server/issues/4068#issuecomment-908683603) and the Plugin API discussion started [here](https://github.com/cdr/code-server/discussions/4072). 

I'm going to close this PR but we would love to get your input on the Plugin API!

**Pull request closed without merging**
