### PR TITLE
Fix path

### PR DESCRIPTION
**Pull request by mberbero**
Fixing rsync path

### CODE REVIEW

**Comment by code-asher** [comment]
I don't believe this is the correct path, see: https://github.com/cdr/code-server/tree/v3.6.1/src/browser/media

**Comment by mberbero** [comment]
> I don't believe this is the correct path, see: https://github.com/cdr/code-server/tree/v3.6.1/src/browser/media

Fix for this cdr:handlebars-templates branch.
https://github.com/cdr/code-server/tree/handlebars-templates

**Comment by code-asher** [comment]
Ohhh I didn't check the target branch name! Cool, I'll come back to this
after I've reviewed the handlebars PR.

**Comment by code-asher** [comment]
Thanks again for this! We ended up changing the directory altogether during code review and I think the rsync path in that branch is correct now.

**Pull request closed without merging**
