### PR TITLE
Updates manifest.json

### PR DESCRIPTION
**Pull request by TheHllm**
Improves usability by making use of fullscreen when installed as pwa.

### CODE REVIEW

**Comment by sr229** [comment]
How does this changes anything? I think it's fine PWA-wise in `standalone mode`

**Comment by TheHllm** [comment]
It makes it use "fullscreen" aka hides the url bar (on mobile browsers e.g. on a tablet) wich is so much better for use on the go.

**Comment by nhooyr** [comment]
@code-asher standalone should work fine. This is a bug in the browsers, I'm going to revert.

**Comment by code-asher** [comment]
Yeah it does work but fullscreen also hides the status bar which felt
like a more immersive editing experience to me. Is there an advantage to
having the status bar show persistently while using code-server?

**Comment by nhooyr** [comment]
The original user mentioned the URL bar not being hidden.

The status bar should be shown imo as that's what normal apps do.

**Comment by orditeck** [comment]
I don't know if my issue could be related to this but since `2.1698-vsc1.41.1`, I can't create multiple "shortcuts" from the same base URL in Chrome.

I was creating one shortcut per project, for example:
- https://code.mywebsite.com/?folder=/Sites/project1 = Shortcut opening in its standalone window
- https://code.mywebsite.com/?folder=/Sites/project2 = Shortcut opening in its standalone window
- https://code.mywebsite.com/?folder=/Sites/project3 = Shortcut opening in its standalone window

Now it always override the latest shortcut I made.

Before `2.1698`, `CrAppModeShortcutID` was always different = multiple shortcuts possible.
After `2.1698`, `CrAppModeShortcutID` is always the same = multiple shortcuts doesn't seem possible.

**Comment by nhooyr** [comment]
I believe your problem is #1132

**Comment by nhooyr** [comment]
Oh, nvm, that's interesting. I'm not sure what's going on. Can you file an issue?

**Pull request merged**
