### PR TITLE
fix(revert): move helm README to docs

### PR DESCRIPTION
**Pull request by jsjoeio**
This reverts the revert now that we fixed the upstream issue with the docs.

Fixes N/A

TODOs
- [x] address Bruno's comments
- [x] `helm.md` should be under Install
- [x] fix link for Helm package manager
- [x] fix badges using the same format in =README=

### CODE REVIEW

**Comment by jsjoeio** [comment]
Hmmm...something is not right here

https://codercom-enql9v6o6-codercom.vercel.app/docs/code-server/latest

image

**Comment by jawnsy** [comment]
@jsjoeio I checked the [Inspect page](https://vercel.com/codercom/codercom/2Ke15ZGUAZPyzdHT1WAVK266snE3/functions) (link shows up in the build/deploy output), it still shows that there's something wrong with the curly braces {} -- @bpmct did you merge the handlebars removal change?

```
[GET] /docs/code-server/latest
14:03:57:09
info - Building code-server/latest
info - Value of CODE_SERVER_DOCS_MAIN_BRANCH is "ce0c2cd0268a2090e903a8047dfd063bd6c75763".
info - Using "ce0c2cd0268a2090e903a8047dfd063bd6c75763" as main content source.
2021-09-03T21:03:57.761Z	7bff6c39-d6eb-4178-bdf3-530514c888ca	ERROR	Error: Parse error on line 285:
...ation    image: {{ .Values.image.reposi
----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP'
    at Parser.parseError (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Parser.parse (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at parseWithoutProcessing (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at HandlebarsEnvironment.parse (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
    at compileInput (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
    at ret (/var/task/product/coder.com/site/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
    at markdownParser (/var/task/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:1538:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /var/task/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:6788:23
RequestId: 7bff6c39-d6eb-4178-bdf3-530514c888ca Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by jsjoeio** [comment]
doesn't look like it 😢

https://github.com/cdr/m/pull/9696

**Comment by BrunoQuaresma** [comment]
Taking a look at why the check returns an error but the action is returning green.

**Comment by BrunoQuaresma** [comment]
I re-run the check job and now it is working. Idk if it was using an old version of the script 🤔

**Comment by jsjoeio** [comment]
> I re-run the check job and now it is working. Idk if it was using an old version of the script 🤔

🤷‍♂️ I'll keep an eye out.

@BrunoQuaresma can we merge https://github.com/cdr/m/pull/9696?

**Comment by BrunoQuaresma** [comment]
@jsjoeio yeap! That is good for me.

**Comment by jsjoeio** [comment]
I need to double-check this branch. I think I messed it up yesterday when I thought I was on another branch.

**Comment by jsjoeio** [comment]
Looks like it's all working now!


image

**Pull request merged**
