### PR TITLE
chore(docs): add README to the docs

### PR DESCRIPTION
**Pull request by BrunoQuaresma**

### CODE REVIEW

**Comment by jsjoeio** [comment]
We're working on the security fix so you can ignore the audit-ci failure.

For additional context, we're adding this because Bruno is working on deploying the code-server docs to a site and we need a Markdown file to render fo the home page. We'll most like change this later!

**Comment by jsjoeio** [comment]
I had an idea. @BrunoQuaresma instead of adding this file to `/docs` and duplicating `README.md`, could we add a script that just copies the `README.md` at the root to the `/docs` folder when we deploy the docs?

**Comment by JammSpread** [comment]
Does it have to be duplicated, couldn't the README just be moved to the 'docs/' folder since according to [this](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes):
> If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.

Although that may decrease the intuitiveness/simplicity of the repository.

**Comment by BrunoQuaresma** [comment]
Thanks @JammSpread I didn't know about this one. I will try that.

**Comment by BrunoQuaresma** [comment]
The badge can be a problem for what we are trying to achieve with these changes - have a doc site for code-server docs. I'm wondering if makes sense we have something similar to what react-query does on their repo: https://github.com/tannerlinsley/react-query. @jsjoeio @JammSpread thoughts?

**Comment by jsjoeio** [comment]
> I'm wondering if makes sense we have something similar to what react-query does on their repo:

Sorry @BrunoQuaresma - a bit dense this morning. What am I looking at in react-query's repo? I see their badges in the README. Or do you mean how the `README` is very short and then they have the `/docs` repo? 

I do like what @JammSpread suggested. If GitHub surfaces the `README.md` that could be a solid approach.

**Comment by BrunoQuaresma** [comment]
>  Or do you mean how the README is very short and then they have the /docs repo?
Yes, I was talking about that.

> I do like what @JammSpread suggested. If GitHub surfaces the README.md that could be a solid approach.
Me too, but I faced some issues trying to load the badge images with our current markdown parser and I was not able to solve 😞. Because of that, I think the first option can be a good approach for now. 

We can have a README on root with the badges and a brief summary, and a docs/README.md with a more complete introduction. What do you think?

**Comment by jsjoeio** [comment]
> We can have a README on root with the badges and a brief summary, and a docs/README.md with a more complete introduction. What do you think?

I think that could work. As long as we add a short blurb like "look in `/docs` for more documentation` or something, should be fine!

**Comment by jsjoeio** [comment]
> I faced some issues trying to load the badge images with our current markdown parser

Would it be better if the badges were listed using HTML instead of markdown? We have options. See https://shields.io/

image

**Comment by bpmct** [comment]
I would be much more in favor of doing one of these options:

1. Use shields.io (like @jsjoeio suggested)
2. Update our hosted docs detect and to hide the shields from the root-level README
3. Change the codecov link (or whatever one is breaking outside of the repo) to show cdr/code-server stats, regardless where it is hosted.
4. Remove the culprit image

Reasoning being:
- We won't have to manually copy over ./README.md -> ./docs/README.md, or set a prescience for doing it (every release, every commit, etc?)
- docs/README.md can simply inform users of the [hosted site](https://coder.com/docs/code-server/latest)

**Comment by bpmct** [comment]
I would also be in favor of a slimmed down ./README.md in favor of a larger one here. Not a fan of the duplication, but if necessary, we can go that route.

**Comment by jsjoeio** [comment]
@BrunoQuaresma anything you need from us to help you move this forward?

**Comment by BrunoQuaresma** [comment]
@jsjoeio I'm just aligning stuff with @bpmct before move forward, thanks for ask.

**Comment by bpmct** [comment]
We will likely be able to render the root-level README (with shields, if we want). So we will likely not need a second README in docs. Still going over details :)

**Comment by bpmct** [comment]
> Does it have to be duplicated, couldn't the README just be moved to the 'docs/' folder since according to [this](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes):
> 
> > If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.
> 
> Although that may decrease the intuitiveness/simplicity of the repository and thus be a bad idea.

@jsjoeio What are your thoughts on moving the readme as suggested above? This would reduce the complexity for the docs site

**Comment by jsjoeio** [comment]
Thanks for the test repo. Seems fine to me too! I'll see if @code-asher or @oxy want to weigh in

**Comment by BrunoQuaresma** [comment]
I opened up a new PR to move the README. I will close this one, when we get that merged to no break the code-server docs build.

**Comment by jsjoeio** [comment]
I see #3663 has been merged. Does that mean we should close this @BrunoQuaresma?

**Comment by BrunoQuaresma** [comment]
@jsjoeio yes, doing it right now.

**Pull request closed without merging**
