### PR TITLE
feat: persist route query to local

### PR DESCRIPTION
**Pull request by fxxjdedd**
Provide a way for the shell script running in the docker container to get the url query.

### CODE REVIEW

**Comment by code-asher** [comment]
Thanks for the contribution! Could you expound on the use case?

**Comment by fxxjdedd** [comment]
Thank you for your reply.
The use case is: the URL of our web ide will carry some dynamic parameters, such as user, project, cluster, etc. These parameters need to be obtained in the debugger and terminal.

**Comment by code-asher** [comment]
Interesting, thanks for the additional details. We already have a file that contains the last visited path in `~/.local/share/code-server/coder.json` (just a bit further down in `getRoot`). Would it work for your use case to add the query variables to the `lastVisited` object in that file instead?

**Comment by fxxjdedd** [comment]
Of course, it will help a lot！


------------------ Original ------------------

**Comment by code-asher** [comment]
Awesome, let's go that route then.

**Comment by fxxjdedd** [comment]
@code-asher 

I made some changes and it works fine locally.

**Comment by fxxjdedd** [comment]
emmm, I have some different opinions:
Although await is clearer, but it&nbsp;will blocks all the code below, but promise.then will not.&nbsp;
On the other hand, if they are written together, the query will be updated using extends, so that when the query becomes empty, the data in the settings will not be updated correctly


------------------ Original ------------------

**Comment by code-asher** [comment]
That's fair, let's leave out the `await`.

We can pass `true` when updating both to use the shallow update. That's actually preferable anyway because the `lastVisited` object should be replaced entirely.

**Comment by code-asher** [comment]
In fact I'm thinking about removing `extends` entirely because I'm not sure we even need a recursive merge.

**Comment by fxxjdedd** [comment]
cool, let‘s have a try!

------------------ Original ------------------

**Pull request merged**
