### PR TITLE
Fix typos in wget url

### PR DESCRIPTION
**Pull request by T45K**
### Describe in detail the problem you had and how this PR fixes it
In url specified by `wget`, there are unnecessary `-`s.

### Is there an open issue you can link to?
Unsure.

### CODE REVIEW

**Comment by deansheather** [comment]
@T45K could you please sign these commits so we can merge them in?

**Comment by T45K** [comment]
@deansheather Sorry for my poor knowledge. I'm a novice at Git and GitHub and I didn't know I could sign my commit. Now, I have signed. Is this OK?

**Comment by deansheather** [comment]
Unfortunately not quite. You'll need to delete the last two commits from
your local repository, then amend the first commit you made with `git
commit --amend -S`.

**Comment by T45K** [comment]
@deansheather Thank you for your advice!
I have fixed them. Please check again.

**Comment by deansheather** [comment]
Thanks!

**Comment by T45K** [comment]
No. Thank YOU!

**Pull request merged**
