### PR TITLE
fix: revert revert and add ssh back into guide docs

### PR DESCRIPTION
**Pull request by jsjoeio**
#4042 broke our docs website, #4060 reverted the change.

> There are 2 problems in there. There are 4 back ticks at the end of one block. Changing the line “```output” to  “```console” should fix it

Thanks to @mterhar, I think we found the issue. 

We're working with @BrunoQuaresma to prevent issues like this in the future.

Related:
- https://github.com/cdr/code-server/pull/4042
- https://github.com/cdr/code-server/pull/4060
- https://github.com/cdr/code-server/discussions/4057

### CODE REVIEW

**Comment by jsjoeio** [comment]
Checked the preview. Looks good! @BrunoQuaresma any idea why the docs are making this shield round?

When I look at it in the browser, it's square like the others. See [here](https://img.shields.io/badge/Terminal-2E2E2E?style=for-the-badge&logo=Windows+Terminal&logoColor=ffffff)

image

**Comment by BrunoQuaresma** [comment]
@jsjoeio I will check it. Probably a random CSS class. Also, when adding badges, it is recommended to make it a link, even if it is only an image. When it is an image, you can make it a link pointing to the image itself. It is how GH does to make their badges inline. You can inspect how our README.md looks like on GH inspecting the badges.

**Comment by BrunoQuaresma** [comment]
@jsjoeio also, looks like we are not closing a code block here: 
Screen Shot 2021-08-31 at 10 37 57
It looks like the `bash` block is inside of another block.

**Comment by jsjoeio** [comment]
> When it is an image, you can make it a link pointing to the image itself. It is how GH does to make their badges inline. You can inspect how our README.md looks like on GH inspecting the badges.

Ah okay, I'll match that.

**Comment by jsjoeio** [comment]
> also, looks like we are not closing a code block here:

Nice catch! I'll fix that too

**Comment by jsjoeio** [comment]
> > When it is an image, you can make it a link pointing to the image itself. It is how GH does to make their badges inline. You can inspect how our README.md looks like on GH inspecting the badges.
> 
> Ah okay, I'll match that.

I just checked and these are already links 🤔 Not sure what else we can do then. 

image

**Comment by jsjoeio** [comment]
Ready for another review! @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
@jsjoeio I sent a PR just fixing the link on the terminal badge.
Screen Shot 2021-09-01 at 10 14 03

**Review by BrunoQuaresma — APPROVED** [review]
LGTM

**Comment by jsjoeio** [comment]
I'll merge after I get this merged in: https://github.com/cdr/code-server/pull/4085

**Comment by im-coder-lg** [comment]
@jsjoeio I need to tell, the ngrok URL changes every time, as well as the port. One time you run ngrok, you get 0.tcp.ngrok.io and port 19028, but the next time you run it, you will get 2.ngrok.io and 10320, and it goes on. So, add `in this case,` to the ngrok guide where the port is mentioned and add a note that the port and the URL always changes so you have to use the URL and the port given on the terminal.

**Comment by jsjoeio** [comment]
Ahh good call @im-coder-lg - thanks for mentioning that!

**Comment by im-coder-lg** [comment]
:+1:

**Pull request merged**
