### PR TITLE
Modify --link arg and README (Cdr Cloud)

### PR DESCRIPTION
**Pull request by JammSpread**

### CODE REVIEW

**Comment by JammSpread** [comment]
Correct me if I'm wrong, but I assume it is not in alpha anymore. Is it in beta or is it released?

**Comment by nhooyr** [comment]
> Correct me if I'm wrong, but I assume it is not in alpha anymore. Is it in beta or is it released?

I'm not personally sure. cc @sreya

**Comment by nhooyr** [comment]
Thanks for contributing @JammSpread

**Comment by nhooyr** [comment]
❤️

**Pull request merged**
