### PR TITLE
VS Code 1.60.0 via Submodule

### LINKED ISSUE #3917: Upgrade to VS Code 1.60
Upgrade to VS Code 1.59

### PR DESCRIPTION
**Pull request by TeffenEllis**
While #4010 resolves some incompatibilities with 1.60.0, it's still in review and needs additional testing. This PR updates `lib/vscode` to use a submodule pointing to our [VS Code fork](https://github.com/cdr/vscode/tree/1.60.0-code-server-patch). Once this is merged, any remaining fork clean up branches will be ported over to the submodule.

Fixes #3917

### Notable changes from upstream

- The log service now defers initialization.
- Several terminal channels were added.
- Serval type definitions were adjusted. 

### How to review this PR

This is a somewhat unusual PR since we don’t yet have a diff to start with, however, I’ve made a branch on our fork with the previous changes form `lib/vscode`. This allows you compare all the changes from upstream, as well as the adjustments to our code to fix them in 1.60.0

https://github.com/cdr/vscode/compare/1.57.1-initial...cdr:1.60.0-code-server-patch

### CODE REVIEW

**Comment by jsjoeio** [comment]
> https://github.com/cdr/code-server/pull/4122/checks?check_run_id=3550356321#step:6:2125

It looks like the postinstall script is failing? Is that because it runs `yarn` inside `lib/vscode` but now that that's a submodule, we need to modify it? just a guess

**Comment by jsjoeio** [comment]
I'm looking at the [list of commits](https://github.com/cdr/vscode/compare/1.57.1-initial...cdr:1.60.0-code-server-patch) and there are 3,600 😮 I'm thinking the only reasonable way to review this is to check it out locally, run it and make sure everything works

**Comment by TeffenEllis** [comment]
@jsjoeio,

> I'm looking at the [list of commits](https://github.com/cdr/vscode/compare/1.57.1-initial...cdr:1.60.0-code-server-patch) and there are 3,600 😮 I'm thinking the only reasonable way to review this is to check it out locally, run it and make sure everything works

This is unfortunately the case until our own tests can run along side upstream’s to ensure we didn’t cause a regression in their code.

>It looks like the postinstall script is failing? Is that because it runs yarn inside lib/vscode but now that that's a submodule, we need to modify it? just a guess

Bingo 😃

**Comment by jsjoeio** [comment]
Dang it! It failed again. 

image

**Pull request closed without merging**
