### PR TITLE
Revamp icons

### LINKED ISSUE #2307: Update Dock Icon
### Update Dock Icon

I want to prefix this with this is super nitpicky. I love code-server, but the current dock icon stands out from other applications in the dock in an unpleasant way. I reworked the current design to match the macOS Big Sur icon style, and I think it looks a lot better (see image below). It's pretty rough, but if you like what you see, I would be happy to work on it more and provide variations for Windows and Linux.

### Before

image

### After

icon in dock

Full icon

### PR DESCRIPTION
**Pull request by nhooyr**
I took our website's SVG favicon and plopped it on a round
white rectangle in Affinity Designer. The I exported it as an SVG and
wrote a script that uses imagemagick to convert to the various sizes and
formats we need.

Closes #2307

Screen Shot 2020-11-30 at 6 48 23 PM

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]
LGTM.

**Comment by reaseno** [comment]
Looks a bit hard to recognize/defect in browser.
I think it would help to make it a bit bigger and use colors.

image

**Comment by nhooyr** [comment]
I used the same icon for everything which I guess was a mistake. The favicon should be a bit bigger I agree.

**Comment by agneevX** [comment]
Re: #2044 

This may be an improvement, however there's even more empty space around the icon.

Old            |  Updated
:-------------------------:|:-------------------------:
image  |  image

**Comment by nhooyr** [comment]
@agneevX It should be fixed in the next release by #2401

**Comment by xPaw** [comment]
This removed background from the svg, so when a dark theme is used in a browser, the icon is visibile.

image

Perhaps add `prefers-color-scheme`?
https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/

**Comment by agneevX** [comment]
A round white background would look great.

**Comment by nhooyr** [comment]
Opened https://github.com/cdr/code-server/issues/2538

**Pull request merged**
