### PR TITLE
Update collaboration.md

### LINKED ISSUE #4280: CodeTogether section in Collaboration.md needs to be updated
Genuitec just shipped CodeTogether 4.2 and as a result the feature list in collaboration.md needs to be updated to provide an accurate account of what is now available.

### PR DESCRIPTION
**Pull request by toddewilliams**
I updated the CodeTogether description to include some enhancements that we just shipped in CodeTogether 4.2. I also added a bit more detail to the feature list and provided some hyperlinks in a couple of places where people would likely appreciate more detail. 

I made no changes to the other sections.

Fixes #4280

### CODE REVIEW

**Review by TeffenEllis — APPROVED** [review]
Thank you so much for sending these changes over.

Much appreciated ✨

**Comment by toddewilliams** [comment]
Glad to contribute! But the build seems to have failed. Anything for me to do here?

**Comment by jsjoeio** [comment]
@toddewilliams 

Is it possible for you to run `yarn fmt` locally? Otherwise, if you checked the box "allow edits from maintainers" then I can do it for you. Just let me know!

image

**Comment by toddewilliams** [comment]
Fortunately, I did check the box to allow edits from maintainers because it's your project and that only seems right. 

So I'd greatly appreciate it if you'd do the needful to push this on through Joe. My days of being in git every day are behind me at this point. Thanks in advance!

**Comment by jsjoeio** [comment]
> Fortunately, I did check the box to allow edits from maintainers because it's your project and that only seems right.

Awesome! (No way for me to know sadly without asking)

Let me see if I can push changes to get this fixed

**Pull request merged**
