### PR TITLE
fix NOTE.txt

### LINKED ISSUE #4504: [Helm chart] Typo in Helm chart notes
In
https://github.com/cdr/code-server/blob/66060408354c223918cb1df4b0cb8849aad4c9c7/ci/helm-chart/templates/NOTES.txt#L20

you forgot the namespace, i.e. `--namespace {{ .Release.Namespace }`

### PR DESCRIPTION
**Pull request by jlandowner**
Fixes #4504

Currently fetching Pod, but I think it is better to use Service directly.

### CODE REVIEW

**Comment by jsjoeio** [comment]
Hey @Matthew-Beckett - do you mind helping me review this PR? I think it looks good but wanted to get your take since you know this part of the codebase better than me!

**Review by jsjoeio — APPROVED** [review]
Thanks for doing this 🎉

**Review by Matthew-Beckett — APPROVED** [review]
Changes don't affect chart function, just "cosmetic".

**Comment by Matthew-Beckett** [comment]
Thanks for your contribution @jlandowner this is definitely better!

❤️

**Pull request merged**
