### PR TITLE
VS Code 1.48.0

### PR DESCRIPTION
**Pull request by code-asher**

### CODE REVIEW

**Comment by nhooyr** [comment]
Thoughts on merging into a `dev` branch and then merging `dev` into `master` when we release?

Would avoid confusion re the version in package.json and documentation updates for things that haven't made it into master.

**Comment by nhooyr** [comment]
Lack of a git subtree is also contributing to massive commits to the patch.

**Comment by code-asher** [comment]
Smaller patchfiles do seem like would help reviewability, and maybe even with conflict resolution. I think many of the core issues remain though so I'd be happier without any patches. :smile:

**Comment by nhooyr** [comment]
Lets hash it out in https://github.com/cdr/code-server/pull/1982

**Comment by nhooyr** [comment]
Whoops, meant to link #1587

**Pull request merged**
