### PR TITLE
Add --enable-proposed-api flag to cli.ts to fix issue with extensions failing

### LINKED ISSUE #1744: Some popular extensions (eg GitHub Pull Requests and Issues) fail on load due to lack of Proposed API support
Expected behavior: Extensions load w/o error, eg GitHub.vscode-pull-request-github
Actual behavior: Extensions fail to load with the following error. 

Ideas for fixing:
1) hardcode --enable-proposed-api flag for vscode (to enable for all extensions).
2) I believe issue #1528 could also fix this by adding the flag to VSCODE_OPTIONS once it exists.

```
[2020-05-28 10:24:10.809] [exthost] [error] Error: [GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
        at a (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:810)
	at Object.t.checkProposedApiEnabled (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:148)
	at Object.registerDecorationProvider (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:906:76)
	at new t.PullRequestsTreeDataProvider (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:547205)
	at /usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:653078
	at Generator.next (<anonymous>)
	at /usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:650859
	at new Promise (<anonymous>)
	at n (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:650607)
	at t.activate (/usr/local/x/home/aderk/.local/share/code-server/extensions/github.vscode-pull-request-github-0.16.0/media/extension.js:1:652378)
	at Function._callActivateOptional (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:825:502)
	at Function._callActivate (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:825:153)
	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:824:94
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
```

- Web Browser: Chrome
- Local OS: Ubuntu
- Remote OS: Ubuntu
- Remote Architecture: AMD64
- `code-server --version`: 3.3.1 6f1309795e1cb930edba68cdc7c3dcaa01da0ab3

### PR DESCRIPTION
**Pull request by aderk**
Fixes #1744
Updates #1981

### CODE REVIEW

**Comment by geiseri** [comment]
Is this PR still valid?

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by code-asher** [comment]
We need to make some modifications according to https://github.com/cdr/code-server/issues/1744#issuecomment-642228856

**Comment by kylecarbs** [comment]
@code-asher thoughts on forking this and making the needed changes?

**Comment by code-asher** [comment]
I think that's a good idea, I'll tackle it this week.

**Comment by code-asher** [comment]
I branched off this here: https://github.com/cdr/code-server/pull/2002

**Pull request closed without merging**
