### PR TITLE
Add Nginx instructions to guide

### PR DESCRIPTION
**Pull request by Niek**
Added Nginx instructions for people who prefer to use this instead of Caddy

See for example issue #770

### CODE REVIEW

**Comment by nhooyr** [comment]
My reasoning to leave this out was that any user that can't setup Nginx without an example should be using Caddy instead. It's better on every front.

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by nhooyr** [comment]
We've had so many issues filed from people just not understanding how to configure nginx.

**Comment by code-asher** [comment]
Yeah maybe it's worth having it just on account of all the issues. If so, we should add a trailing slash to the `proxy_pass` line since that makes sub-paths work and I've had to explain that at least a few times in various issues I think.

**Comment by Niek** [comment]
IMHO it never hurts to have *too* much documentation. Even if Caddy is good for 95% of the users, I think those 5% with existing nginx installs would appreciate it.

I've added the trailing / now.

**Comment by code-asher** [comment]
Thanks for the contribution!

**Pull request merged**
