### PR TITLE
Support multiple file encodings

### LINKED ISSUE #1017: support other encodings than UTF-8
Related: https://github.com/microsoft/vscode/issues/79275

I have fixed this issue in my local environment, and I'd like to make a pull request if you want.

### PR DESCRIPTION
**Pull request by LeuisKen**

### CODE REVIEW

**Comment by nhooyr** [comment]
Thanks for contributing @LeuisKen!

Can you please rebase on latest master?

**Comment by LeuisKen** [comment]
> Thanks for contributing @LeuisKen!
> 
> Can you please rebase on latest master?

done

**Comment by code-asher** [comment]
I might not be able to test this out today but if not I'll definitely get to it tomorrow.

**Comment by code-asher** [comment]
I think in an ideal world we'd extract all the encoding/decoding into `browser/textFileService.ts` to match the way native VS Code does it (all the encoding seems to be handled in `nativeTextFileService.ts`) but it's probably not worth the extra effort since VS Code will put out their own fix eventually at which time we'll need to remove ours.

**Comment by nhooyr** [comment]
Based on discussion in #1017 we're going to close this for now in anticipation of the upstream fixes.

**Pull request closed without merging**
