### PR TITLE
docker: Allow passing $DOCKER_USER to set the username in the container

### LINKED ISSUE #881: Ability to change username inside the docker container?
Hi. it would be nice to be able to pass in the username and uid|gid as environmental variables when launching container.

So we dont have to use a name `coder` and use something specific to the user.

### PR DESCRIPTION
**Pull request by nhooyr**
Needs to be reflected in the documentation and the dockerhub description
now.

Closes #881

cc @avaidyam

### CODE REVIEW

**Comment by avaidyam** [comment]
At first glance, this looks fantastic! It solves a definitely minor but important problem. Thanks @nhooyr!

**Comment by nhooyr** [comment]
Should be good now.

**Comment by code-asher** [comment]
Actually no I see that gets deleted.

**Comment by nhooyr** [comment]
Weird. 🤔

**Comment by nhooyr** [comment]
Can confirm the exec issue, debugging.

**Comment by nhooyr** [comment]
Ah, you need to set pass `-u $UID` so unrelated to this PR @code-asher

**Comment by code-asher** [comment]
Ahhhhh yup that worked! Now I'm getting
```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "chdir to cwd (\"/home/coder\") set in config.json failed: no such file or directory": unknown
```
Is that happening to you?

**Comment by nhooyr** [comment]
Huh, no, my shell opened fine.

**Comment by nhooyr** [comment]
i.e `docker exec -u $UID -it 5c3a18e17438 bash -li` works perfectly for me.

**Comment by nhooyr** [comment]
We discussed on slack and the error is unrelated to this PR.

**Pull request merged**
