### PR TITLE
media: Improve icon size

### PR DESCRIPTION
**Pull request by nhooyr**
See https://github.com/cdr/code-server/pull/2383#issuecomment-738024951

Screen Shot 2020-12-04 at 2 26 25 AM

On the left is the new icon, right is the old one.

Dock icon looks the same but is slightly larger.

Screen Shot 2020-12-04 at 2 24 59 AM

Thanks for reporting @reaseno!

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

**Comment by agneevX** [comment]
@nhooyr is the dock icon from Chrome A2HS?

**Comment by nhooyr** [comment]
@agneevX Yes!

**Comment by reaseno** [comment]
Now the favicon isn't visible when having black browser tabs because the white background is gone 😞
I recommend additional colors.

**Comment by nhooyr** [comment]
Opened https://github.com/cdr/code-server/issues/2538

**Pull request merged**
