### PR TITLE
docs(install): add Azure and Heroku

### LINKED ISSUE #2711: code-server for azure app service
Can you prepare the code-server docker image for Azure's app services?

### PR DESCRIPTION
**Pull request by bpmct**
Adds an initial section in install.md for deploying code-server to app engines.

closes #2711,  #2686

### CODE REVIEW

**Comment by bpmct** [comment]
@jsjoeio You had also mentioned mentioning [awesome-code-server](https://github.com/bpmct/awesome-code-server) in the docs. I can make it an official `cdr` repo, and then add it in the FAQ. Should I include that in this PR or another?

**Comment by bpmct** [comment]
if this is better suited as a FAQ piece, let me know. wasn't sure what made the most sense with docs.

**Review by jsjoeio — APPROVED** [review]
Looks great! Thanks for doing this Ben 🎉

**Comment by jsjoeio** [comment]
> You had also mentioned mentioning awesome-code-server in the docs. I can make it an official cdr repo, and then add it in the FAQ. Should I include that in this PR or another?

Up to you! Whatever you prefer. You can either add it here and re-request a review, or merge this and open a separate PR

**Comment by jsjoeio** [comment]
bump @bpmct

**Comment by bpmct** [comment]
oops, forgot to push. wasn't quite sure where to put it/how to word it in the FAQ. whatever fits best for the overall style I'm down for @jsjoeio

**Review by jsjoeio — APPROVED** [review]
LGTM! Ship it 🚢

**Pull request merged**
