### PR TITLE
Use ptyHostService

### LINKED ISSUE #2276: Persistant terminal session on tab refresh
Eclipse Theia keeps any terminal sessions open when the tab is refreshed. Would it be possible to have this same functionality in code-server? Either enabled at all times, or with a flag.

### PR DESCRIPTION
**Pull request by code-asher**
Most of this was a straightforward replacement of our code with theirs
but I also removed `getDefaultShellAndArgs` since it seems the reference
implementation no longer does that either.

Fixes #2276.

### CODE REVIEW

**Review by oxy — APPROVED** [review]
Really nice work, and win for maintainability! :tada:
Let's merge after e2e tests pass!

**Review by jsjoeio — APPROVED** [review]
Woo! Awesome work. Excited to see this in action 🎉

**Comment by oxy** [comment]
Pulled locally, is failing with:
```
[IPC Library: Pty Host] Error: ENOENT: no such file or directory, open '/var/home/oxy/Downloads/code-server-3.9.3-linux-amd64/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js'
```

(Downloaded release package from CI)

**Comment by oxy** [comment]
Tested locally, and terminal + persistence now works! Woohoo!

**Pull request merged**
