### PR TITLE
Update FAQ for proper hashed-password generation

### PR DESCRIPTION
**Pull request by confusedguy9**
Get rid of the automatically inserted trailing newline.

### CODE REVIEW

**Comment by jsjoeio** [comment]
Thanks for the doc fix @confusedguy9! Do you mind changing your base branch to `master`? Then I can approve and merge this. Thank you!

**Comment by confusedguy9** [comment]
I've changed the base branch as requested.

**Comment by nhooyr** [comment]
Let's use `printf` here instead of `echo`! That way the same example should work correctly across all unix based OSes like the BSDs as well.

**Comment by code-asher** [comment]
Thanks again for the PR! I went ahead and merged https://github.com/cdr/code-server/pull/2533 which has the `printf` fix.

**Pull request closed without merging**
