### PR TITLE
docs: fix confusing sentence in pull requests section

### PR DESCRIPTION
**Pull request by shiv-tyagi**
This PR fixes a sentence in Pull request section which was less understandable on the first go. 

## Checklist

- [x] updated `CHANGELOG.md`

### CODE REVIEW

**Comment by jsjoeio** [comment]
Thanks for fixing this! @shiv-tyagi 🎉

We would love to make sure you get credit in the next release. Do you mind updating the `CHANGELOG`? (and also updating/rebasing your branch)

**Comment by shiv-tyagi** [comment]
It's my pleasure to contribute to the community. As I am a complete beginner to open source, can you guide me a bit about how to update CHANGELOG?

**Comment by jsjoeio** [comment]
Sure thing! The `CHANGELOG` lives at the root of the repo [here](https://github.com/cdr/code-server/blob/main/CHANGELOG.md). We ask that contributors add a line there to note their PR change. This saves us time for cutting releases because then we can copy the changes and use in the release notes.

1. Open `CHANGELOG.md` on your branch
2. Since this is a change for the next version, look at the comment "Add next version above previous version but below this line using the template" and add the next version
3. Your change is a documentation change so add it to the bulleted list under "Documentation". I would do something like " - docs: fix confusing sentence in pull requests section #3460 @shiv-tyagi"
4. Commit and push change

(P.S. planning to add more docs about updating the `CHANGELOG` so it will be easier in the future.)

**Comment by shiv-tyagi** [comment]
I have committed the changes in changelog. If I review the same. If anything needs to be changes, please let me know.

**Review by jsjoeio — APPROVED** [review]
Looks great! Thanks again @shiv-tyagi 🎉

**Comment by jsjoeio** [comment]
Apologies @shiv-tyagi - can you please run `yarn fmt` locally and push up your changes? I would do it, but it doesn't seem like I can unless you check the box "Allow edits from maintainers" https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by shiv-tyagi** [comment]
I have allowed edits from maintainers. I can't figure it out what 'yarn fmt' and how to do this. It would be great if you elaborate a bit more @jsjoeio .

**Comment by shiv-tyagi** [comment]
> I have allowed edits from maintainers. I can't figure it out what 'yarn fmt' and how to do this. It would be great if you elaborate a bit more @jsjoeio .

I figured it out. I installed yarn locally and then I did run 'yarn fmt'. It made some changes in CHANGELOG.md . I hope I did it correctly @jsjoeio .

**Comment by jsjoeio** [comment]
Hooray! (Sorry I should have elaborated). Glad you got it though! I think it should be good then!

**Pull request merged**
