### PR TITLE
update image tag to v2 in yaml

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

### Describe in detail the problem you had and how this PR fixes it
Update image tag to v2

### CODE REVIEW

**Comment by yeya24** [comment]
> I don't get the point of this PR. If this was having problems with deploying you may not have exposed the port properly. We use 8080 by default. This will not work.

So can you deploy code-server in your k8s environment with the default yaml? I have tried it and it failed.

**Comment by yeya24** [comment]
Error:
```
➜  examples git:(master) kp service/code-server -n code-server 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
E0926 23:17:03.453318    9495 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 5e4dc4bd6c1413afe3fe56f04a70311b0c79da2746bc69c4146a0d61d47e10ab, uid : exit status 1: 2019/09/27 03:17:02 socat[5168] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
E0926 23:17:03.453510    9495 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 5e4dc4bd6c1413afe3fe56f04a70311b0c79da2746bc69c4146a0d61d47e10ab, uid : exit status 1: 2019/09/27 03:17:02 socat[5169] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8080
Handling connection for 8080
E0926 23:17:03.460688    9495 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 5e4dc4bd6c1413afe3fe56f04a70311b0c79da2746bc69c4146a0d61d47e10ab, uid : exit status 1: 2019/09/27 03:17:02 socat[5170] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
E0926 23:17:03.461991    9495 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 5e4dc4bd6c1413afe3fe56f04a70311b0c79da2746bc69c4146a0d61d47e10ab, uid : exit status 1: 2019/09/27 03:17:02 socat[5171] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8080
Handling connection for 8080
```

Then check about the logs of code-server pod:
``` yaml
➜  examples git:(master) ✗ kg po -n code-server
NAME                           READY   STATUS    RESTARTS   AGE
code-server-79dccb9f86-l96m7   1/1     Running   0          92s
➜  examples git:(master) ✗ klo code-server-79dccb9f86-l96m7 -n code-server
(node:6) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server v1.1156-vsc1.33.1
INFO  Additional documentation: http://github.com/cdr/code-server
INFO  Initializing {"data-dir":"/home/coder/.local/share/code-server","extensions-dir":"/home/coder/.local/share/code-server/extensions","working-dir":"/home/coder/project","log-dir":"/home/coder/.cache/code-server/logs/20190927031909135"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md
INFO
INFO  Password: e712bb1d04007e245a645bdd
INFO
INFO  Started (click the link below to open):
INFO  https://localhost:8443/
INFO
WARN  stderr {"data":"(node:19) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
```

Code-server is running in 8443 instead of 8080

**Comment by sr229** [comment]
Unfortunately, it seems that `latest` is v1, but we written all of the docs for v2. Please edit your local copy to a v2 tag and run it again. v1 is a deprecated version.

**Comment by yeya24** [comment]
> Unfortunately, it seems that `latest` is v1, but we written all of the docs for v2. Please edit your local copy to a v2 tag and run it again. v1 is a deprecated version.

OK. So I will update the tag in this PR.

**Pull request merged**
