### PR TITLE
chore: replace eslint-import-resolver-alias with resolver-typescript

### PR DESCRIPTION
**Pull request by JounQin**
As title

### CODE REVIEW

**Comment by JounQin** [comment]
cc @jsjoeio

**Comment by jsjoeio** [comment]
Hi @JounQin - thank you for submitting this PR! Can you explain why you've opened this PR and what this fixes or what benefits this brings? I'm not familiar with `resolver-typescript`

**Comment by JounQin** [comment]
@jsjoeio As you can see at https://github.com/cdr/code-server/pull/4546/files#diff-3894e4104cda190617684d0dc5d55e39e49c63cc6955edf4a446b91ae086bbd2, [eslint-import-resolver-typescript](https://github.com/alexgorbatchev/eslint-import-resolver-typescript) resolves `.ts/.tsx/.d.ts` and `@types/*` packages correctly and there is no need to ignore "unresolved" errors anymore.

**Comment by jsjoeio** [comment]
Ahh! (That code was before me)

Now I see. Thanks for fixing/replacing this! You can ignore the Docs preview but as long as the rest of CI passes (it should), we can merge!

**Review by jsjoeio — APPROVED** [review]
Thank you so much for doing this!

**Comment by JounQin** [comment]
@jsjoeio Shall we merge then.

**Comment by jsjoeio** [comment]
> Shall we merge then?

Yes! Apologies I was out Thurs/Fri but should get this in today :D Thanks for the bump!

**Pull request merged**
