### PR TITLE
FAQ.md: Add mention of hashedPassword

### LINKED ISSUE #2451: Mention hashedPassword in FAQ
See https://github.com/cdr/code-server/issues/2225#issuecomment-742082627

Just would be nice to demonstrate how you can use  `sha256sum` to generate the hash.

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #2451

### CODE REVIEW

**Review by oxy — APPROVED** [review]
LGTM! Not sure if we want to put a warning that the password once hashed can't be recovered - should be obvious but may not be.

**Comment by nhooyr** [comment]
> Not sure if we want to put a warning that the password once hashed can't be recovered - should be obvious but may not be.

I think we're good. That's the point of hashing after all.

**Comment by immanuelfodor** [comment]
Will this work with Docker environment variable like `PASSWORD` but as `HASHEDPASSWORD`?

**Comment by immanuelfodor** [comment]
Nevermind, I've found it in the binary options: 

--password             The password for password authentication (can only be passed in via $PASSWORD or the config file).                                     

--hashed-password      The password hashed with SHA-256 for password authentication (can only be passed in via $HASHED_PASSWORD or the config file).                                 Takes precedence over 'password'.

**Pull request merged**
