### PR TITLE
refactor: clean up testing files

### PR DESCRIPTION
**Pull request by jsjoeio**
I accidentally merged a PR that didn't have a file formatted correctly and it made CI on `main` fail. This fixes that but also clean ups some testing files to be better organized.

### CODE REVIEW

**Comment by jawnsy** [comment]
Ah, just curious, shouldn't the same formatting checks run on PRs and main? How'd it get merged in the first place?

**Review by jawnsy — APPROVED** [review]

**Comment by jsjoeio** [comment]
I hit enable auto-merge which says "Automatically merge when all requirements are met." - let me checking the repo settings

**Comment by jsjoeio** [comment]
image

Weird, pre-build is not required, but should be? Enabling now: cc @oxy and @code-asher

**Comment by jsjoeio** [comment]
actually, i bet i broke it when i changed it to "Pre-Build" instead of "Pre-build"

**Comment by jsjoeio** [comment]
argh, auto update imports didn't work lol fixing

**Comment by jawnsy** [comment]
Haha, I dislike auto merge because of these sorts of problems, but I see how it can be helpful :man_shrugging:

**Comment by jsjoeio** [comment]
I feel ya, luckily this has only happened once or twice

**Comment by jsjoeio** [comment]
Moment of truth

**Comment by code-asher** [comment]
Hmm but we require end-to-end tests which requires pre-build? Is it sneaking in the auto-merge in the gaps before the next check starts??

**Comment by jsjoeio** [comment]
I guess it might be? Maybe it's a bug? I went into the settings and added "Pre-Build" as a required check. Maybe it's sneaking in because the previous run had both of those passing? I'm not too sure

**Pull request merged**
