### PR TITLE
docs(contributing): Update links

### PR DESCRIPTION
**Pull request by vapurrmaid**

### CODE REVIEW

**Review by jsjoeio — APPROVED** [review]
Thanks for fixing this ♥️

**Comment by vapurrmaid** [comment]
@jsjoeio any idea why CI keeps failing for this?

**Comment by jsjoeio** [comment]
> @jsjoeio any idea why CI keeps failing for this?

Your doc update is toooo big @vapurrmaid - you broke our machine 😛

image

JK. Hmm I don't know how to delete things or get more space lol cc @code-asher

**Comment by jsjoeio** [comment]
I can also take a look first thing tomorrow

**Comment by vapurrmaid** [comment]
> I can also take a look first thing tomorrow

Not a huge rush or anything!

**Comment by jsjoeio** [comment]
I'm going to merge this and open up a separate issue for us to take care of the ci/linux-arm64 issue

**Pull request merged**
