### PR TITLE
Remove duplication in dependencies

### PR DESCRIPTION
**Pull request by maksimr**
“devDependencies” already contains “@types/tar-fs”

### CODE REVIEW

**Comment by nhooyr** [comment]
Weird, not sure why yarn didn't fix that automatically, thanks!

**Comment by nhooyr** [comment]
(waiting for CI to pass)

**Comment by nhooyr** [comment]
Looks like yarn.lock needs changes, can you run `yarn` again and push?

**Comment by maksimr** [comment]
@nhooyr done

**Pull request merged**
