### PR TITLE
Add linkup command to improve link functionality 

### PR DESCRIPTION
**Pull request by TeffenEllis**
TBD

### CODE REVIEW

**Review by jsjoeio — APPROVED** [review]
I think this all looks good but probably want a second opinion from @kylecarbs (plus CI is failing)

**Review by kylecarbs — APPROVED** [review]

**Comment by jsjoeio** [comment]
> error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.

Do we need to update the `yarn.lock` file?

**Comment by TeffenEllis** [comment]
This PR likely needs to be rebased and updated with the latest vscode commit.

**Comment by jsjoeio** [comment]
> This PR likely needs to be rebased and updated with the latest vscode commit

I wasn't sure what you meant by "updated with the latest vscode commit":

## Option 1 

1. go to https://github.com/cdr/vscode
2. hit Fetch upstream
3. grab the latest vscode commit
4. use that in `vendor/package.json`

## Option 2

1. go to https://github.com/cdr/vscode
2. grab the latest vscode commit: `affcb6753278c014d1eea83664e6fbf5d702852a`
3. use that in `vendor/package.json`

## Option 3. 
1. look at `main` branch in code-server
2. use vscode commit in `vendor/package.json`

I rebased and went with Option 3: `9cb5fb3759f46b10bc66e676fa7f44c51e84824b`

I hope that's right. I'll wait for you to check before we merge this.

**Comment by TeffenEllis** [comment]
Tentatively resolved in #4010

**Pull request closed without merging**
