### PR TITLE
Create code-server.sls

### PR DESCRIPTION
**Pull request by korzq**
## Describe in detail the problem you had and how this PR fixes it
Their is no salt state for deployment using salt.

So I made one :P

### CODE REVIEW

**Comment by korzq** [comment]
forgot to add some files, gonna make a new one. Apologies.

**Comment by korzq** [comment]
I've also put the salt state in https://github.com/korzq/code-server-salt if it should be linked instead of being in the repo.

**Comment by sr229** [comment]
Thanks for the conntribution, however, since we don't want to compensate for many use cases, we don't want to support such. I'll be closing this off for now. If its fine for you, just update your repo whenever we release something?

**Comment by korzq** [comment]
Allright 👍

**Pull request closed without merging**
