### PR TITLE
Add sample deployment for Google Kubernetes Engine

### PR DESCRIPTION
**Pull request by tadashi0713**
### Describe in detail the problem you had and how this PR fixes it
Added sample code for Google Kubernetes Engine(GKE)
Mainly differs PersistentVolume compared to AWS

### Is there an open issue you can link to?
No

### CODE REVIEW

**Comment by nhooyr** [comment]
We already have a k8s example at https://github.com/cdr/code-server/blob/master/doc/examples/kubernetes.yaml

That should suffice imo.

**Comment by nhooyr** [comment]
Likewise for AWS at https://github.com/cdr/code-server/blob/master/doc/examples/kubernetes.aws.yaml

I guess we should include this GKE example there as `kubernetes.gke.yaml`.

**Comment by sr229** [comment]
Based on @nhooyr's feedback I think we can close this one. We'll revert to a vendor-neutral config instead.

**Comment by nhooyr** [comment]
@sr229 Please open a new issue for that so we don't forget.

**Pull request closed without merging**
