### PR TITLE
Drop duplicate Helm values from values.yaml

### LINKED ISSUE #4441: duplicate values in helm chart example
@Matthew-Beckett. I noticed a couple duplicate values in the example [values.yaml](https://github.com/cdr/code-server/blob/main/ci/helm-chart/values.yaml) such as `securityContext` and `serviceAccount`.

Happy to contribute with a PR, but your guidance on which example to keep would be helpful :)

### PR DESCRIPTION
**Pull request by Matthew-Beckett**
Fixes #4441 

- Drop duplicate PodSecurityContext usage
- Drop duplicate ServiceAccount usage

### CODE REVIEW

**Review by jsjoeio — APPROVED** [review]
Awesome! Thanks for fixing this so quickly! ♥️

**Comment by jsjoeio** [comment]
I think we just merged a PR that fixes the e2e tests so maybe you can rebase onto `main`? I would do it but I'm not sure if it will let me 🤔

**Review by jsjoeio — APPROVED** [review]
🤞 Please work!

**Comment by Matthew-Beckett** [comment]
@jsjoeio is this ready for merge? I don't want main getting to far out of sync and having to do a fat rebase again 😅

**Comment by jsjoeio** [comment]
Yes! Thanks for the bump! Merging :D

**Pull request merged**
