### PR TITLE
Add social badges

### PR DESCRIPTION
**Pull request by bpmct**

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

**Review by code-asher — APPROVED** [review]
LGTM. Thoughts on putting it inline at the top like https://github.com/facebook/react? Although I guess it wouldn't fit unless we shortened some text a bit.

**Comment by bpmct** [comment]
@code-asher how's that?

**Comment by code-asher** [comment]
I think it looks awesome!

**Review by nhooyr — APPROVED** [review]
nice!

**Comment by code-asher** [comment]
Our checks don't seem to run when they're from another repo. Gonna go ahead and merge this though.

**Pull request merged**
