### PR TITLE
Update VS code to 1.49.3

### LINKED ISSUE #1015: iOS copy and cut keyboard shortcuts are not working
- `code-server` 1.1156-vsc1.33.1
- OS Version: iPadOS 13.1 Beta 4 (on iPad Pro 2018 12.9)

## Description

The keyboard shortcuts for copying and cutting text don‘t work. Changing the shortcuts in the code-server settings to something different of „cmd+c“ and „cmd+x“ does not help.

## Steps to Reproduce

1. Open and edit a file.
2. Try using „cmd+c“ or „cmd+x“.
3. Change the shortcuts in the settings.
4. Fail again.

### PR DESCRIPTION
**Pull request by code-asher**
I didn't have to make any changes except add a new file to the `coder.js` build script.

Might fix #1015 but I don't have any means of testing it.

### CODE REVIEW

**Comment by pavlovcik** [comment]
I cloned and tried to build -- do you know what I might be missing?

```
yarn build v0.24.6
(node:13301) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ ./ci/build/build-code-server.sh
src/node/app/vscode.ts:15:8 - error TS2307: Cannot find module '../../../lib/vscode/src/vs/server/ipc' or its corresponding type declarations.

15 } from "../../../lib/vscode/src/vs/server/ipc"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:6:32 - error TS2307: Cannot find module '../../lib/vscode/src/vs/server/ipc' or its corresponding type declarations.

6 import { Args as VsArgs } from "../../lib/vscode/src/vs/server/ipc"
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:123:3 - error TS2322: Type '{ auth: { type: typeof AuthType; description: string; }; password: { type: "string"; description: string; }; cert: { type: typeof OptionalString; path: true; description: string; }; "cert-key": { ...; }; ... 27 more ...; verbose: { ...; }; }' is not assignable to type 'Options<Required<Args>>'.
  Object literal may only specify known properties, and '"user-data-dir"' does not exist in type 'Options<Required<Args>>'.

123   "user-data-dir": { type: "string", path: true, description: "Path to the user data directory." },
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:292:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

292   if (args.verbose) {
               ~~~~~~~

src/node/cli.ts:309:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

309       args.verbose = true
               ~~~~~~~

src/node/cli.ts:313:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

313       args.verbose = false
               ~~~~~~~

src/node/cli.ts:317:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

317       args.verbose = false
               ~~~~~~~

src/node/cli.ts:321:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

321       args.verbose = false
               ~~~~~~~

src/node/cli.ts:325:12 - error TS2339: Property 'verbose' does not exist on type 'Args'.

325       args.verbose = false
               ~~~~~~~

src/node/cli.ts:335:8 - error TS7053: Element implicitly has an 'any' type because expression of type '"user-data-dir"' can't be used to index type 'Args'.
  Property 'user-data-dir' does not exist on type 'Args'.

335   if (!args["user-data-dir"]) {
           ~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:337:5 - error TS7053: Element implicitly has an 'any' type because expression of type '"user-data-dir"' can't be used to index type 'Args'.
  Property 'user-data-dir' does not exist on type 'Args'.

337     args["user-data-dir"] = paths.data
        ~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:340:8 - error TS7053: Element implicitly has an 'any' type because expression of type '"extensions-dir"' can't be used to index type 'Args'.
  Property 'extensions-dir' does not exist on type 'Args'.

340   if (!args["extensions-dir"]) {
           ~~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:341:5 - error TS7053: Element implicitly has an 'any' type because expression of type '"extensions-dir"' can't be used to index type 'Args'.
  Property 'extensions-dir' does not exist on type 'Args'.

341     args["extensions-dir"] = path.join(args["user-data-dir"], "extensions")
        ~~~~~~~~~~~~~~~~~~~~~~

src/node/cli.ts:341:40 - error TS7053: Element implicitly has an 'any' type because expression of type '"user-data-dir"' can't be used to index type 'Args'.
  Property 'user-data-dir' does not exist on type 'Args'.

341     args["extensions-dir"] = path.join(args["user-data-dir"], "extensions")
                                           ~~~~~~~~~~~~~~~~~~~~~

src/node/entry.ts:6:49 - error TS2307: Cannot find module '../../lib/vscode/src/vs/server/ipc' or its corresponding type declarations.

6 import { CliMessage, OpenCommandPipeArgs } from "../../lib/vscode/src/vs/server/ipc"
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/node/entry.ts:45:48 - error TS7053: Element implicitly has an 'any' type because expression of type '"user-data-dir"' can't be used to index type 'Args'.
  Property 'user-data-dir' does not exist on type 'Args'.

45   logger.info(`Using user-data-dir ${humanPath(args["user-data-dir"])}`)
                                                  ~~~~~~~~~~~~~~~~~~~~~

src/node/entry.ts:47:50 - error TS7053: Element implicitly has an 'any' type because expression of type '"extensions-dir"' can't be used to index type 'Args'.
  Property 'extensions-dir' does not exist on type 'Args'.

47   logger.trace(`Using extensions-dir ${humanPath(args["extensions-dir"])}`)
                                                    ~~~~~~~~~~~~~~~~~~~~~~


Found 17 errors.

error Command failed with exit code 2.
nv:code-server Pavlovcik$
```

**Comment by code-asher** [comment]
It looks like the patch wasn't applied. Check out https://github.com/cdr/code-server/blob/v3.5.0/doc/CONTRIBUTING.md#development-workflow. In particular the `yarn vscode` step is what applies the patch.

**Comment by DAddYE** [comment]
Hi, I got the same error and was after `yarn vscode`. Any idea what could be?

**Comment by DAddYE** [comment]
> Hi, I got the same error and was after `yarn vscode`. Any idea what could be?

Oh, figure out, basically I did `yarn vscode:diff`, which wiped the patch :)

Works well, and I confirm fixed the issue on iPad.

**Comment by code-asher** [comment]
Thank you for testing it!!

**Review by nhooyr — APPROVED** [review]
🔥

**Pull request merged**
