### PR TITLE
Docker minimum image

### PR DESCRIPTION
**Pull request by jylenhof**
Issue I created to follow this pull request:
#2459

### CODE REVIEW

**Comment by oxy** [comment]
Thanks for your contribution! Unfortunately, I'm not sure if a slim image will fit code-server's intended use case, since developers would be connecting to the container and using it as a full-fledged development environment, and many expect to have the usual suite of command line tools.

**Comment by nhooyr** [comment]
Yup to echo @oxy's sentiments we intentionally used the larger image.

Perhaps we should offer a `-slim` variant.

**Comment by nhooyr** [comment]
See my comments in #2459

**Comment by nhooyr** [comment]
Again, I hear you @jylenhof! Appreciate your contributions. Hopefully next release we have an official slim image that satisfies your needs :)

**Pull request closed without merging**
